// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFKCHCg-GsWil4dywv05qZ_XUWJk_FW20',
    appId: '1:353788783151:web:45765e2f49dd4dac1334da',
    messagingSenderId: '353788783151',
    projectId: 'bastirchef-3aeef',
    authDomain: 'bastirchef-3aeef.firebaseapp.com',
    storageBucket: 'bastirchef-3aeef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD0TkMvTQ5FKKbkaSIi8Kt6NBcPamPuYc',
    appId: '1:353788783151:android:602a63d4aaee46401334da',
    messagingSenderId: '353788783151',
    projectId: 'bastirchef-3aeef',
    storageBucket: 'bastirchef-3aeef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYATPf_8SwNfir-fKpf9R1j87ggN0ZPPI',
    appId: '1:353788783151:ios:778aef98e9fe4f691334da',
    messagingSenderId: '353788783151',
    projectId: 'bastirchef-3aeef',
    storageBucket: 'bastirchef-3aeef.appspot.com',
    iosBundleId: 'com.example.bastirchef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYATPf_8SwNfir-fKpf9R1j87ggN0ZPPI',
    appId: '1:353788783151:ios:02d486fe8deebc801334da',
    messagingSenderId: '353788783151',
    projectId: 'bastirchef-3aeef',
    storageBucket: 'bastirchef-3aeef.appspot.com',
    iosBundleId: 'com.example.bastirchef.RunnerTests',
  );
}
